# Generated by Django 5.2.15 on 2026-06-24 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección Física')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('provincia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('provincia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('motocicleta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_asignado', to='operaciones.motocicleta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('Directo', 'Directo'), ('Con Receta', 'Con Receta'), ('Traslado', 'Traslado'), ('Reenvío', 'Reenvío')], max_length=50)),
                ('direccion_destino', models.CharField(max_length=250, verbose_name='Dirección de Destino')),
                ('comuna_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna de Destino')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ruta', 'En ruta'), ('Entregado', 'Entregado')], default='En ruta', max_length=50)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_asignados', to='operaciones.motorista')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='operaciones.farmacia')),
            ],
        ),
    ]
