# Generated by Django 5.2.15 on 2026-06-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='comuna',
            field=models.CharField(default='Santiago', max_length=100),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
