# Generated by Django 5.2.15 on 2026-07-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_motorista_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PANA', 'Pana / Falla Mecánica'), ('ACCIDENTE', 'Accidente de Tránsito'), ('CLIMA', 'Problemas Climáticos'), ('CLIENTE', 'Cliente no responde / Dirección Incorrecta'), ('OTRO', 'Otro Imprevisto')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Detalles del problema')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente / Sin Revisar'), ('EN_PROCESO', 'En Proceso de Solución'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='operaciones.movimiento')),
            ],
        ),
    ]
