# Generated by Django 5.2.15 on 2026-07-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocicleta',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'En Mantenimiento')], default='Disponible', max_length=20),
        ),
    ]
